export const THEME = {
  canvasBg: "#0D0C0B",
  surface0: "#0D0C0B",
  surface1: "#161412",
  surface2: "#1E1C19",
  surface3: "#262320",
  surface4: "#2E2B27",
  textPrimary: "#F2EDE6",
  textSecondary: "#9B9087",
  textTertiary: "#5C5650",
  textOnAccent: "#0D0C0B",
  accent: "#E8A838",
  accentHover: "#F0B84A",
  accentMuted: "#3D2E0E",
  accentBorder: "#5C4418",
  success: "#3D9970",
  successMuted: "#0D2B1F",
  danger: "#E85438",
  dangerMuted: "#2B110A",
  warning: "#E8A838",
  ai: "#7B61FF",
  aiMuted: "#1A1535",
  aiBorder: "#332A6B",
  stageComplete: "#3D9970",
  stageActive: "#E8A838",
  stagePending: "#2E2B27",
  fontMono: '"Geist Mono", "JetBrains Mono", "Fira Code", monospace',
  fontSans: '"Inter", "DM Sans", system-ui, sans-serif',
  space: [0, 4, 8, 12, 16, 24, 32, 48, 64],
  radius: { sm: 6, md: 10, lg: 16, xl: 24, full: 9999 },
  shadow: {
    sm: "0 2px 8px rgba(0,0,0,0.4)",
    md: "0 4px 20px rgba(0,0,0,0.5)",
    lg: "0 8px 40px rgba(0,0,0,0.6)",
    ai: "0 4px 24px rgba(123,97,255,0.25)",
  },
  spring: { type: "spring", stiffness: 320, damping: 28 },
  springFast: { type: "spring", stiffness: 480, damping: 32 },
  easeOut: { duration: 0.18, ease: [0.16, 1, 0.3, 1] },
  stageTrans: { duration: 0.55, ease: [0.32, 0, 0.16, 1] },
};

export const STAGES = [
  {
    id: "primary",
    label: "Primary Pack",
    shortLabel: "PRI",
    description: "Folding carton · Paperboard",
    icon: "package",
    substrateTypes: ["paperboard", "pouch", "bottle", "tube"],
  },
  {
    id: "pack",
    label: "Pack into Carton",
    shortLabel: "PCK",
    description: "How many primary units fit in a transit carton",
    icon: "carton",
    substrateTypes: ["all"],
    note: "Corrugated or solid board transit box auto-sized here",
  },
  {
    id: "pallet",
    label: "Pallet",
    shortLabel: "PAL",
    description: "Stack cartons on pallet and optimise pattern",
    icon: "pallet",
    substrateTypes: ["all"],
  },
  {
    id: "report",
    label: "Report",
    shortLabel: "RPT",
    description: "Engineering report and export",
    icon: "report",
    substrateTypes: ["all"],
  },
];
